[global]

[logger]

[client]
showErrorDetails = "none"
toolbarMode = "auto"

[theme]
# primaryColor = "forestGreen"
# textColor = "red"
# linkColor="darkOrchid"
# backgroundColor = "pink"
# secondaryBackgroundColor = "orange"

[theme.sidebar]
# backgroundColor = "lightGray"
# textColor = "black"
# linkColor = "blue"
